# Generated by Django 5.0.2 on 2024-02-15 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchfield',
            name='field_value_bool',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='matchfield',
            name='field_value_integer',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
