# Generated by Django 5.0.2 on 2024-02-15 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0002_alter_matchfield_field_value_bool_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchfield',
            name='field_value_bool',
        ),
        migrations.RemoveField(
            model_name='matchfield',
            name='field_value_integer',
        ),
        migrations.CreateModel(
            name='MatchFieldResponseBool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_value_bool', models.BooleanField(default=False)),
                ('match_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scouting.matchfield')),
            ],
        ),
        migrations.CreateModel(
            name='MatchFieldResponseInteger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_value_integer', models.IntegerField(default=None)),
                ('match_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scouting.matchfield')),
            ],
        ),
    ]
