# Generated by Django 5.0.2 on 2024-02-15 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0003_remove_matchfield_field_value_bool_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='auton_fields',
        ),
        migrations.RemoveField(
            model_name='match',
            name='endgame_fields',
        ),
        migrations.RemoveField(
            model_name='match',
            name='post_match_fields',
        ),
        migrations.RemoveField(
            model_name='match',
            name='pre_match_fields',
        ),
        migrations.RemoveField(
            model_name='match',
            name='teleop_fields',
        ),
        migrations.AddField(
            model_name='game',
            name='auton_fields',
            field=models.ManyToManyField(blank=True, null=True, related_name='+', to='scouting.matchfield'),
        ),
        migrations.AddField(
            model_name='game',
            name='endgame_fields',
            field=models.ManyToManyField(blank=True, null=True, related_name='+', to='scouting.matchfield'),
        ),
        migrations.AddField(
            model_name='game',
            name='post_match_fields',
            field=models.ManyToManyField(blank=True, null=True, related_name='+', to='scouting.matchfield'),
        ),
        migrations.AddField(
            model_name='game',
            name='pre_match_fields',
            field=models.ManyToManyField(blank=True, null=True, related_name='+', to='scouting.matchfield'),
        ),
        migrations.AddField(
            model_name='game',
            name='teleop_fields',
            field=models.ManyToManyField(blank=True, null=True, related_name='+', to='scouting.matchfield'),
        ),
    ]
