# Generated by Django 5.0.2 on 2024-02-15 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0004_remove_match_auton_fields_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='auton_fields',
            field=models.ManyToManyField(blank=True, related_name='+', to='scouting.matchfield'),
        ),
        migrations.AlterField(
            model_name='game',
            name='endgame_fields',
            field=models.ManyToManyField(blank=True, related_name='+', to='scouting.matchfield'),
        ),
        migrations.AlterField(
            model_name='game',
            name='post_match_fields',
            field=models.ManyToManyField(blank=True, related_name='+', to='scouting.matchfield'),
        ),
        migrations.AlterField(
            model_name='game',
            name='pre_match_fields',
            field=models.ManyToManyField(blank=True, related_name='+', to='scouting.matchfield'),
        ),
        migrations.AlterField(
            model_name='game',
            name='teleop_fields',
            field=models.ManyToManyField(blank=True, related_name='+', to='scouting.matchfield'),
        ),
    ]
