# Generated by Django 5.0.2 on 2024-02-16 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0006_alter_match_options_matchdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
