# Generated by Django 5.0.2 on 2024-02-16 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0007_event_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='year',
            field=models.IntegerField(unique=True),
        ),
    ]
