# Generated by Django 5.0.2 on 2024-02-16 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0010_matchfieldresponse_delete_matchfieldresponsebool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchfieldresponseinteger',
            name='match_field',
        ),
        migrations.CreateModel(
            name='ScoutDataSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_bool', models.BooleanField()),
                ('response_int', models.IntegerField()),
                ('match_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scouting.matchdata')),
                ('match_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scouting.matchfield')),
            ],
        ),
        migrations.AddField(
            model_name='matchdata',
            name='scout_response',
            field=models.ManyToManyField(through='scouting.ScoutDataSelection', to='scouting.matchfield'),
        ),
        migrations.DeleteModel(
            name='MatchFieldResponse',
        ),
        migrations.DeleteModel(
            name='MatchFieldResponseInteger',
        ),
    ]
