# Generated by Django 5.0.2 on 2024-02-16 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0011_remove_matchfieldresponseinteger_match_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchdata',
            name='scout_response',
        ),
        migrations.AddField(
            model_name='matchdata',
            name='match_field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scouting.matchfield'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchdata',
            name='response_bool',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchdata',
            name='response_int',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ScoutDataSelection',
        ),
    ]
