# Generated by Django 5.0.2 on 2024-02-16 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0012_remove_matchdata_scout_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchdata',
            name='response_bool',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='matchdata',
            name='response_int',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
