# Generated by Django 5.0.2 on 2024-02-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0015_alter_event_options_alter_game_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbaApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
