# Generated by Django 5.0.2 on 2024-02-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0016_tbaapikey'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbaapikey',
            options={'verbose_name_plural': 'The Blue Alliance API Keys'},
        ),
        migrations.AddField(
            model_name='event',
            name='tba_event_key',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
