# Generated by Django 5.0.2 on 2024-02-18 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0017_alter_tbaapikey_options_event_tba_event_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='teams',
            field=models.ManyToManyField(blank=True, to='scouting.team'),
        ),
    ]
