# Generated by Django 5.0.2 on 2024-02-18 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0019_pitscoutdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pitscoutdata',
            options={'verbose_name_plural': 'Pit scout data'},
        ),
        migrations.AddField(
            model_name='matchdata',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scouting.event'),
            preserve_default=False,
        ),
    ]
