# Generated by Django 5.0.2 on 2024-02-18 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0020_alter_pitscoutdata_options_matchdata_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchdata',
            options={'verbose_name_plural': 'Match data'},
        ),
        migrations.AlterField(
            model_name='matchdata',
            name='response_bool',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
