# Generated by Django 5.0.2 on 2024-02-22 01:02

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0021_alter_matchdata_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitscoutdata',
            name='can_climb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pitscoutdata',
            name='can_climb_2_robots',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pitscoutdata',
            name='can_go_under_stage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pitscoutdata',
            name='can_lift_another_robot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pitscoutdata',
            name='can_place_note_in_trap',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pitscoutdata',
            name='can_score_amp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pitscoutdata',
            name='can_score_speaker_from_other_position',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pitscoutdata',
            name='can_score_speaker_from_subwoofer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pitscoutdata',
            name='has_april_tag_recognition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pitscoutdata',
            name='has_crisp_boombers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pitscoutdata',
            name='has_floor_pickup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pitscoutdata',
            name='has_player_station_pickup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pitscoutdata',
            name='has_variable_angle_shooter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pitscoutdata',
            name='has_vision_object_detection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pitscoutdata',
            name='linear_speed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pitscoutdata',
            name='robot_heigh_in',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pitscoutdata',
            name='robot_length_in',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pitscoutdata',
            name='robot_weight_lbs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pitscoutdata',
            name='robot_width_in',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pitscoutdata',
            name='shoots_down_into_amp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pitscoutdata',
            name='shoots_up_into_amp',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MatchData2024',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('arrived_on_field_on_time', models.BooleanField(default=True)),
                ('start_with_note', models.BooleanField(default=False)),
                ('dead_on_arrival', models.BooleanField(default=False)),
                ('startingLocation', models.CharField(max_length=20, null=True)),
                ('left_community_zone', models.BooleanField(default=False)),
                ('moved', models.BooleanField(default=False)),
                ('a_stopped', models.BooleanField(default=False)),
                ('amp_notes_scored', models.IntegerField(default=0)),
                ('speaker_notes_scored', models.IntegerField(default=0)),
                ('notes_picked_up_from_wing', models.IntegerField(default=0)),
                ('notes_picked_up_from_center', models.IntegerField(default=0)),
                ('time_to_centerline_note', models.IntegerField(default=0)),
                ('e_stopped', models.BooleanField(default=False)),
                ('communication_lost', models.BooleanField(default=False)),
                ('notes_scored_from_subwoofer', models.IntegerField(default=0)),
                ('notes_scored_from_elesewhere', models.IntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scouting.match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scouting.team')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
