# Generated by Django 5.0.2 on 2024-02-22 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0023_rename_has_crisp_boombers_pitscoutdata_crisp_boombers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pitscoutdata',
            old_name='can_climb',
            new_name='April Tag Recognition',
        ),
        migrations.RenameField(
            model_name='pitscoutdata',
            old_name='can_climb_2_robots',
            new_name='Can detect obstacles with vision processing',
        ),
        migrations.RenameField(
            model_name='pitscoutdata',
            old_name='can_go_under_stage',
            new_name='Can go under stage',
        ),
        migrations.RenameField(
            model_name='pitscoutdata',
            old_name='can_lift_another_robot',
            new_name='Can lift another robot',
        ),
        migrations.RenameField(
            model_name='pitscoutdata',
            old_name='can_place_note_in_trap',
            new_name='Can place note in trap',
        ),
        migrations.RenameField(
            model_name='pitscoutdata',
            old_name='can_score_amp',
            new_name='Can score in amp',
        ),
        migrations.RenameField(
            model_name='pitscoutdata',
            old_name='can_score_speaker_from_other_position',
            new_name='Can score in speaker from elsewhere on field',
        ),
        migrations.RenameField(
            model_name='pitscoutdata',
            old_name='can_score_speaker_from_subwoofer',
            new_name='Can score in speaker from subwoofer',
        ),
        migrations.RenameField(
            model_name='pitscoutdata',
            old_name='has_april_tag_recognition',
            new_name='Climb',
        ),
        migrations.RenameField(
            model_name='pitscoutdata',
            old_name='has_floor_pickup',
            new_name='Climb with another robot',
        ),
        migrations.RenameField(
            model_name='pitscoutdata',
            old_name='description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='pitscoutdata',
            old_name='has_player_station_pickup',
            new_name='Floor Pickup',
        ),
        migrations.RenameField(
            model_name='pitscoutdata',
            old_name='linear_speed',
            new_name='Linear speed, (meters per second)',
        ),
        migrations.RenameField(
            model_name='pitscoutdata',
            old_name='has_variable_angle_shooter',
            new_name='Player Station Pickup',
        ),
        migrations.RenameField(
            model_name='pitscoutdata',
            old_name='robot_heigh_in',
            new_name='Robot height (inches)',
        ),
        migrations.RenameField(
            model_name='pitscoutdata',
            old_name='robot_length_in',
            new_name='Robot length (inches)',
        ),
        migrations.RenameField(
            model_name='pitscoutdata',
            old_name='robot_weight_lbs',
            new_name='Robot weight (lbs)',
        ),
        migrations.RenameField(
            model_name='pitscoutdata',
            old_name='robot_width_in',
            new_name='Robot width (inches)',
        ),
        migrations.RenameField(
            model_name='pitscoutdata',
            old_name='has_vision_object_detection',
            new_name='Shoots downwards into amp',
        ),
        migrations.RenameField(
            model_name='pitscoutdata',
            old_name='shoots_down_into_amp',
            new_name='Shoots upwards into amp',
        ),
        migrations.RenameField(
            model_name='pitscoutdata',
            old_name='shoots_up_into_amp',
            new_name='Variable Angle Shooter',
        ),
    ]
