# Generated by Django 5.0.2 on 2024-02-23 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0024_rename_can_climb_pitscoutdata_april_tag_recognition_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchdata2024',
            old_name='startingLocation',
            new_name='starting_location',
        ),
    ]
