# Generated by Django 5.0.2 on 2024-02-24 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0025_rename_startinglocation_matchdata2024_starting_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pitscoutdata',
            old_name='Description',
            new_name='description',
        ),
    ]
