# Generated by Django 5.0.2 on 2024-02-28 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0026_rename_description_pitscoutdata_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchdata2024',
            options={'permissions': (('stands_scout_teams', 'Can stands scout teams'),)},
        ),
        migrations.AlterModelOptions(
            name='pitscoutdata',
            options={'permissions': (('pit_scout_teams', 'Can pit scout teams'),), 'verbose_name_plural': 'Pit scout data'},
        ),
        migrations.DeleteModel(
            name='MatchData',
        ),
    ]
