# Generated by Django 5.0.2 on 2024-02-28 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0027_alter_matchdata2024_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchdata2024',
            options={'permissions': (('stands_scout_team', 'Can stands scout teams'),)},
        ),
    ]
