# Generated by Django 5.0.2 on 2024-03-02 04:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0028_alter_matchdata2024_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchdata2024',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pitscoutdata',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
