# Generated by Django 5.0.2 on 2024-03-11 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0028_alter_matchdata2024_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchdata2024',
            old_name='speaker_notes_missed',
            new_name='notes_missed',
        ),
        migrations.RemoveField(
            model_name='matchdata2024',
            name='defense_scale',
        ),
        migrations.RemoveField(
            model_name='matchdata2024',
            name='moved',
        ),
        migrations.RemoveField(
            model_name='matchdata2024',
            name='notes_dropped',
        ),
        migrations.RemoveField(
            model_name='matchdata2024',
            name='notes_picked_up_from_center',
        ),
        migrations.RemoveField(
            model_name='matchdata2024',
            name='notes_picked_up_from_floor',
        ),
        migrations.RemoveField(
            model_name='matchdata2024',
            name='notes_picked_up_from_player_station',
        ),
        migrations.RemoveField(
            model_name='matchdata2024',
            name='notes_picked_up_from_wing',
        ),
        migrations.RemoveField(
            model_name='matchdata2024',
            name='notes_scored_from_elesewhere',
        ),
        migrations.RemoveField(
            model_name='matchdata2024',
            name='notes_scored_from_subwoofer',
        ),
        migrations.RemoveField(
            model_name='matchdata2024',
            name='shoots_from_free_space_to_speaker',
        ),
        migrations.RemoveField(
            model_name='matchdata2024',
            name='shoots_from_podium_to_speaker',
        ),
        migrations.RemoveField(
            model_name='matchdata2024',
            name='shoots_from_subwoofer_to_speaker',
        ),
        migrations.AddField(
            model_name='matchdata2024',
            name='notes_picked_up',
            field=models.IntegerField(default=0),
        ),
    ]
