# Generated by Django 5.0.2 on 2024-03-11 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0029_rename_speaker_notes_missed_matchdata2024_notes_missed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchdata2024',
            name='time_to_centerline_note',
        ),
    ]
