# Generated by Django 5.0.2 on 2024-03-16 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0030_remove_matchdata2024_time_to_centerline_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='endgame_fields',
        ),
        migrations.RemoveField(
            model_name='game',
            name='post_match_fields',
        ),
        migrations.RemoveField(
            model_name='game',
            name='teleop_fields',
        ),
        migrations.RemoveField(
            model_name='game',
            name='pre_match_fields',
        ),
        migrations.RemoveField(
            model_name='game',
            name='auton_fields',
        ),
        migrations.DeleteModel(
            name='MatchField',
        ),
    ]
