# Generated by Django 5.0.2 on 2024-03-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0031_remove_game_endgame_fields_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchdata2024',
            old_name='amp_notes_scored',
            new_name='teleop_amp_notes_scored',
        ),
        migrations.RenameField(
            model_name='matchdata2024',
            old_name='notes_missed',
            new_name='teleop_notes_missed',
        ),
        migrations.RenameField(
            model_name='matchdata2024',
            old_name='speaker_notes_scored',
            new_name='teleop_speaker_notes_scored',
        ),
        migrations.RemoveField(
            model_name='matchdata2024',
            name='notes_picked_up',
        ),
        migrations.AddField(
            model_name='matchdata2024',
            name='auton_amp_notes_scored',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchdata2024',
            name='auton_notes_picked_up',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchdata2024',
            name='auton_speaker_notes_scored',
            field=models.IntegerField(default=0),
        ),
    ]
