# Generated by Django 5.0.2 on 2024-04-04 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0032_rename_amp_notes_scored_matchdata2024_teleop_amp_notes_scored_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchdata2024',
            name='comments',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
