# Generated by Django 5.0.2 on 2025-02-13 00:16

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0034_matchdata2024_teleop_notes_passed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pitscoutdata',
            old_name='Crisp Boombers',
            new_name='crisp_boomers',
        ),
        migrations.RemoveField(
            model_name='pitscoutdata',
            name='April Tag Recognition',
        ),
        migrations.RemoveField(
            model_name='pitscoutdata',
            name='Can detect obstacles with vision processing',
        ),
        migrations.RemoveField(
            model_name='pitscoutdata',
            name='Can go under stage',
        ),
        migrations.RemoveField(
            model_name='pitscoutdata',
            name='Can lift another robot',
        ),
        migrations.RemoveField(
            model_name='pitscoutdata',
            name='Can place note in trap',
        ),
        migrations.RemoveField(
            model_name='pitscoutdata',
            name='Can score in amp',
        ),
        migrations.RemoveField(
            model_name='pitscoutdata',
            name='Can score in speaker from elsewhere on field',
        ),
        migrations.RemoveField(
            model_name='pitscoutdata',
            name='Can score in speaker from subwoofer',
        ),
        migrations.RemoveField(
            model_name='pitscoutdata',
            name='Climb',
        ),
        migrations.RemoveField(
            model_name='pitscoutdata',
            name='Climb with another robot',
        ),
        migrations.RemoveField(
            model_name='pitscoutdata',
            name='Floor Pickup',
        ),
        migrations.RemoveField(
            model_name='pitscoutdata',
            name='Linear speed, (meters per second)',
        ),
        migrations.RemoveField(
            model_name='pitscoutdata',
            name='Player Station Pickup',
        ),
        migrations.RemoveField(
            model_name='pitscoutdata',
            name='Robot height (inches)',
        ),
        migrations.RemoveField(
            model_name='pitscoutdata',
            name='Robot length (inches)',
        ),
        migrations.RemoveField(
            model_name='pitscoutdata',
            name='Robot weight (lbs)',
        ),
        migrations.RemoveField(
            model_name='pitscoutdata',
            name='Robot width (inches)',
        ),
        migrations.RemoveField(
            model_name='pitscoutdata',
            name='Shoots downwards into amp',
        ),
        migrations.RemoveField(
            model_name='pitscoutdata',
            name='Shoots upwards into amp',
        ),
        migrations.RemoveField(
            model_name='pitscoutdata',
            name='Variable Angle Shooter',
        ),
        migrations.AddField(
            model_name='pitscoutdata',
            name='auton_paths',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='pitscoutdata',
            name='auton_picture',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='pitscoutdata',
            name='friendly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pitscoutdata',
            name='intake_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pitscoutdata',
            name='robot_picture',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='pitscoutdata',
            name='type_drivebase',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='MatchData2025',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('defense_text', models.CharField(max_length=1000, null=True)),
                ('counter_defense_text', models.CharField(max_length=1000, null=True)),
                ('human_player', models.CharField(max_length=1000, null=True)),
                ('compatibility', models.CharField(max_length=1000, null=True)),
                ('other_comments', models.CharField(max_length=1000, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scouting.match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scouting.team')),
            ],
            options={
                'permissions': (('stands_scout_team', 'Can stands scout teams'),),
            },
        ),
        migrations.DeleteModel(
            name='MatchData2024',
        ),
    ]
