# Generated by Django 5.0.2 on 2025-02-13 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0035_rename_crisp_boombers_pitscoutdata_crisp_boomers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('ranking_score', models.FloatField()),
                ('matches_played', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scouting.event')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scouting.team')),
            ],
            options={
                'unique_together': {('team', 'event')},
            },
        ),
    ]
