# Generated by Django 5.0.2 on 2025-03-06 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0036_teamranking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchdata2025',
            old_name='compatibility',
            new_name='compatibility_with_alliance_members',
        ),
        migrations.RenameField(
            model_name='matchdata2025',
            old_name='counter_defense_text',
            new_name='defense_effectiveness',
        ),
        migrations.RenameField(
            model_name='matchdata2025',
            old_name='human_player',
            new_name='human_player_accuracy',
        ),
        migrations.RenameField(
            model_name='pitscoutdata',
            old_name='auton_picture',
            new_name='auton_picture_1',
        ),
        migrations.RenameField(
            model_name='pitscoutdata',
            old_name='robot_picture',
            new_name='robot_picture_1',
        ),
        migrations.RemoveField(
            model_name='matchdata2025',
            name='defense_text',
        ),
        migrations.AddField(
            model_name='matchdata2025',
            name='scoring_accuracy_or_effectiveness',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='pitscoutdata',
            name='auton_picture_2',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='pitscoutdata',
            name='auton_picture_3',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='pitscoutdata',
            name='robot_picture_2',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='teamranking',
            name='auto_coral_count',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='teamranking',
            name='ccwm',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='teamranking',
            name='dpr',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='teamranking',
            name='foul_count',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='teamranking',
            name='l1_coral',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='teamranking',
            name='l2_coral',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='teamranking',
            name='l3_coral',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='teamranking',
            name='l4_coral',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='teamranking',
            name='net_algae_count',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='teamranking',
            name='opr',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='teamranking',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamranking',
            name='wall_algae_count',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='pitscoutdata',
            name='auton_paths',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
