# Generated by Django 5.0.2 on 2025-03-06 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0038_remove_teamranking_ranking_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamranking',
            name='matches_played',
        ),
    ]
