# Generated by Django 5.0.2 on 2025-03-08 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0039_remove_teamranking_matches_played'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamranking',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
