# Generated by Django 5.0.2 on 2025-03-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0040_alter_teamranking_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitscoutdata',
            name='auton_picture_1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='pitscoutdata',
            name='auton_picture_2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='pitscoutdata',
            name='auton_picture_3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='pitscoutdata',
            name='robot_picture_1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='pitscoutdata',
            name='robot_picture_2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
