# Generated by Django 5.0.2 on 2025-03-23 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0041_alter_pitscoutdata_auton_picture_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamranking',
            name='endGameBargePoints',
            field=models.FloatField(default=0.0),
        ),
    ]
