# Generated by Django 5.0.2 on 2025-03-23 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0042_teamranking_endgamebargepoints'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamranking',
            old_name='endGameBargePoints',
            new_name='end_game_barge_points',
        ),
    ]
