# Generated by Django 5.0.2 on 2025-03-23 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0043_rename_endgamebargepoints_teamranking_end_game_barge_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pitscoutdata',
            old_name='friendly',
            new_name='friendly_or_cool',
        ),
    ]
