# Generated by Django 5.0.2 on 2025-03-23 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0044_rename_friendly_pitscoutdata_friendly_or_cool'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pitscoutdata',
            old_name='auton_paths',
            new_name='auton_paths_or_description',
        ),
    ]
