# Generated by Django 5.0.2 on 2025-04-03 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0045_rename_auton_paths_pitscoutdata_auton_paths_or_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamranking',
            name='alliance_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamranking',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamranking', to='scouting.team'),
        ),
    ]
