# Generated by Django 5.0.2 on 2025-04-03 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0046_teamranking_alliance_number_alter_teamranking_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchdata2025',
            name='climb_time',
            field=models.IntegerField(null=True),
        ),
    ]
