# Generated by Django 5.0.2 on 2025-04-03 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0048_alter_matchdata2025_climb_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchdata2025',
            name='climb_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
