# Generated by Django 5.0.2 on 2025-04-04 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0049_alter_matchdata2025_climb_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamranking',
            name='priority',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
