from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0050_alter_teamranking_priority'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MatchData2025',
            new_name='MatchData2026',
        ),
        migrations.RenameField(
            model_name='matchdata2026',
            old_name='climb_time',
            new_name='tower_climb_time',
        ),
        migrations.RemoveField(
            model_name='teamranking',
            name='auto_coral_count',
        ),
        migrations.RemoveField(
            model_name='teamranking',
            name='end_game_barge_points',
        ),
        migrations.RemoveField(
            model_name='teamranking',
            name='l1_coral',
        ),
        migrations.RemoveField(
            model_name='teamranking',
            name='l2_coral',
        ),
        migrations.RemoveField(
            model_name='teamranking',
            name='l3_coral',
        ),
        migrations.RemoveField(
            model_name='teamranking',
            name='l4_coral',
        ),
        migrations.RemoveField(
            model_name='teamranking',
            name='net_algae_count',
        ),
        migrations.RemoveField(
            model_name='teamranking',
            name='wall_algae_count',
        ),
        migrations.AddField(
            model_name='teamranking',
            name='auto_tower_points',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='teamranking',
            name='copr_breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='teamranking',
            name='endgame_tower_points',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='teamranking',
            name='energized_achieved',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='teamranking',
            name='foul_points',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='teamranking',
            name='g206_penalty',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='teamranking',
            name='hub_auto_fuel_count',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='teamranking',
            name='hub_endgame_fuel_count',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='teamranking',
            name='hub_first_active_shift_count',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='teamranking',
            name='hub_second_active_shift_count',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='teamranking',
            name='hub_shift_1_fuel_count',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='teamranking',
            name='hub_shift_2_fuel_count',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='teamranking',
            name='hub_shift_3_fuel_count',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='teamranking',
            name='hub_shift_4_fuel_count',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='teamranking',
            name='hub_teleop_fuel_count',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='teamranking',
            name='hub_total_fuel_count',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='teamranking',
            name='hub_transition_fuel_count',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='teamranking',
            name='hub_uncounted',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='teamranking',
            name='major_foul_count',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='teamranking',
            name='minor_foul_count',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='teamranking',
            name='supercharged_achieved',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='teamranking',
            name='total_auto_points',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='teamranking',
            name='total_teleop_points',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='teamranking',
            name='total_tower_points',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='teamranking',
            name='traversal_achieved',
            field=models.FloatField(default=0.0),
        ),
    ]
