# Generated by Django 5.0.2 on 2026-03-06 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0051_2026_data_model_updates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamranking',
            name='foul_count',
        ),
        migrations.RemoveField(
            model_name='teamranking',
            name='hub_first_active_shift_count',
        ),
        migrations.RemoveField(
            model_name='teamranking',
            name='hub_second_active_shift_count',
        ),
        migrations.RemoveField(
            model_name='teamranking',
            name='hub_uncounted',
        ),
    ]
