# Generated by Django 5.0.2 on 2026-03-07 04:14

import scouting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0052_remove_fictional_2026_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitscoutdata',
            name='auton_picture_1',
            field=models.ImageField(blank=True, null=True, upload_to=scouting.models.unique_pit_image_path),
        ),
        migrations.AlterField(
            model_name='pitscoutdata',
            name='auton_picture_2',
            field=models.ImageField(blank=True, null=True, upload_to=scouting.models.unique_pit_image_path),
        ),
        migrations.AlterField(
            model_name='pitscoutdata',
            name='auton_picture_3',
            field=models.ImageField(blank=True, null=True, upload_to=scouting.models.unique_pit_image_path),
        ),
        migrations.AlterField(
            model_name='pitscoutdata',
            name='robot_picture_1',
            field=models.ImageField(blank=True, null=True, upload_to=scouting.models.unique_pit_image_path),
        ),
        migrations.AlterField(
            model_name='pitscoutdata',
            name='robot_picture_2',
            field=models.ImageField(blank=True, null=True, upload_to=scouting.models.unique_pit_image_path),
        ),
    ]
