# Generated by Django 5.0.2 on 2026-03-07 04:48

import scouting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0054_rename_boomers_add_climb_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_logo',
            field=models.ImageField(blank=True, null=True, upload_to=scouting.models.unique_team_logo_path),
        ),
    ]
