# Generated by Django 5.0.2 on 2026-03-07 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0055_team_team_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitscoutdata',
            name='can_robot_drive_under_trench',
            field=models.BooleanField(default=False),
        ),
    ]
