# Generated by Django 5.0.2 on 2026-03-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0056_pitscoutdata_can_robot_drive_under_trench'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitscoutdata',
            name='frc_nexus_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pitscoutdata',
            name='pit_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
