# Generated by Django 5.0.2 on 2026-03-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0057_pitscoutdata_frc_nexus_url_pitscoutdata_pit_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='NexusApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'FRC Nexus API Keys',
            },
        ),
    ]
