# Generated by Django 5.0.2 on 2026-03-07 17:34

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0058_nexusapikey'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('red_score', models.IntegerField(blank=True, null=True)),
                ('blue_score', models.IntegerField(blank=True, null=True)),
                ('red_rp', models.FloatField(blank=True, null=True)),
                ('blue_rp', models.FloatField(blank=True, null=True)),
                ('is_final', models.BooleanField(default=False)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='scouting.match')),
            ],
            options={
                'verbose_name_plural': 'Match results',
            },
        ),
    ]
