# Generated by Django 5.0.2 on 2026-03-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0059_matchresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchresult',
            name='blue_climb_success',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='red_climb_success',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
