# Generated by Django 5.0.2 on 2026-03-07 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0060_matchresult_blue_climb_success_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamranking',
            name='ranking_points',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
