# Generated by Django 5.0.2 on 2026-03-08 02:35

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0061_teamranking_ranking_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayoffMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('tba_match_key', models.CharField(max_length=50, unique=True)),
                ('comp_level', models.CharField(max_length=4)),
                ('set_number', models.IntegerField(blank=True, null=True)),
                ('match_number', models.IntegerField()),
                ('red_alliance_number', models.IntegerField(blank=True, null=True)),
                ('blue_alliance_number', models.IntegerField(blank=True, null=True)),
                ('is_final', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playoff_matches', to='scouting.event')),
                ('team_blue_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scouting.team')),
                ('team_blue_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scouting.team')),
                ('team_blue_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scouting.team')),
                ('team_red_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scouting.team')),
                ('team_red_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scouting.team')),
                ('team_red_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scouting.team')),
            ],
            options={
                'verbose_name_plural': 'Playoff matches',
            },
        ),
    ]
