# Generated by Django 5.0.2 on 2026-04-12 15:40

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0062_playoffmatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='PitDashboardLiveStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('source_timestamp', models.DateTimeField(blank=True, null=True)),
                ('match_label', models.CharField(blank=True, default='', max_length=50)),
                ('blue_score', models.CharField(blank=True, default='?', max_length=16)),
                ('red_score', models.CharField(blank=True, default='?', max_length=16)),
                ('game_time', models.CharField(blank=True, default='?', max_length=16)),
                ('match_started', models.BooleanField(blank=True, null=True)),
                ('last_raw_payload', models.JSONField(blank=True, default=dict)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pit_dashboard_live_status', to='scouting.event')),
            ],
            options={
                'verbose_name_plural': 'Pit dashboard live status',
            },
        ),
    ]
