# Generated by Django 5.0.2 on 2026-04-16 16:17

import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0063_pitdashboardlivestatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='LivestreamRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('source_url', models.URLField()),
                ('output_file', models.CharField(max_length=255)),
                ('ffmpeg_pid', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('assignment_note', models.CharField(blank=True, default='', max_length=120)),
                ('assigned_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livestream_recordings', to='scouting.match')),
                ('assigned_playoff_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livestream_recordings', to='scouting.playoffmatch')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scouting.event')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
