# Generated by Django 5.0.2 on 2026-04-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0064_livestreamrecording'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestreamrecording',
            name='assignment_completed',
            field=models.BooleanField(default=False),
        ),
    ]
